# Generated by Django 4.1.3 on 2022-12-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="description",
            field=models.CharField(max_length=500),
        ),
    ]
