# Generated by Django 4.1.3 on 2022-12-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projeler",
            name="category",
        ),
    ]
